language: elixir

elixir:
  - 1.3.1

otp_release:
  - 18.2.1

addons:
  postgresql: '9.4'

before_script:
  - git config --global user.email "rap@example.com"
  - git config --global user.name "Rui Pereira"
  - psql -c 'create database api_test;' -U postgres
  - mix do ecto.create, ecto.migrate

script:
  - MIX_ENV=dev mix deps.get
  - gem install overcommit
  - overcommit --sign
  - overcommit -r
  - mix test

deploy:
  provider: heroku
  api_key:
    secure: txRxOREqMj7HXV4xL+Fxy+S0rx9BvBJlmSW6ZeHWpSrZMFmjc8LFu9rFHd03+lK9q7milcs6WxqgAmcqkCr79W3w5SZQPJbkbDVcuMMyyQwa5t9fHJi1vqTXtKS0z35re2ys5c1w0ziEYoqal7cLCbLWQo/wTBPpp9nwXTP3QH3Wm1VxVlGK6+0OKMy2wMksw0mMrhCeEqaLMmV3C2Vx0ygobIW5LWLtZbRl4C9U/xznhJhJJoBLKpiN+dUXlLo2jV68mYKAxrxTcQthrI5Q/u27nOT69/GIMtnIbvJrYFkNwhWUp0pOacCKqdey+HE7NV505B0QL4a3OZIadKMPQL6YM/AefD55xf+Q2aDk4kiaCYq2ycPMepfw1qeVZxvKn5vSJgfpmXzxQRIHgSr5u7IoIPms6WiMdfJVAObSbmW6CJ/Ggu02ze7N5JbyNB9gKQL4tbd30Kud3OUj9+kKOYRp11wvwvk3cmeCHJoo3R1v/aj6iB7sLJQwkl9LtMQjx9ix647gwj98gxb1I/DBn43UZ/G4WfYjKPRPmubxFHAFooGdZVesDUjjDmRouZ7Jes7kWCQGav94fP6Tiyz7ygJU6GDAhAGABEd+Zrl51NauztHwmMnTsejg5mfetUnVpaFvAjDGaNAVoGYN6qwUf+H2yYNZ8XZAVfgnbj3XOSM=
  app: warm-plateau-55663
  on:
    repo: blackcucaracha/api

cache:
  directories:
    - _build
    - deps
